#!/usr/bin/env node
const { writeFileSync } = require('fs');
const { EOL } = require('os');
const yargs = require('yargs/yargs');
const parseCsvFile = require('@fast-csv/parse').parseFile;

async function run(options){
    const socOutput = await parseCSVData(options.socfile); 
    const clocOutput = await parseCSVData(options.clocfile);
    const combinedLines = clocOutput.map((cloc) => {
        const fileName = cloc.filename;
        const matchingSocEntry = socOutput.find((socEntry) => {
            return socEntry.entity === fileName;
        });
        return `${fileName},${cloc.code},${matchingSocEntry.soc}`;
    });
    combinedLines.unshift('filename,lines,soc');
    writeFileSync(options.output, combinedLines.join(EOL), 'UTF8');
}

async function parseCSVData(filename){
    const rows = [];
    return new Promise((resolve, reject) => {
        parseCsvFile(filename, { headers: true })
            .on('data', row => rows.push(row))
            .on('end', () => resolve(rows))
            .on('error', reject);
    });
}

const arguments = yargs(process.argv.slice(2)).argv;
run(arguments);